FROM continuumio/anaconda3:latest
COPY . /usr/app/
EXPOSE 5000
WORKDIR /usr/app/
RUN conda config --append channels conda-forge
RUN conda install --file requirements.txt
RUN python -c 'import nltk; nltk.download("punkt")'
CMD python server.py